name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    # ruff lint and format checks
    name: code quality check
    uses: ./.github/workflows/reusable-python-checks.yml
    with:
      python-version: "3.13"
      run-lint: true
      run-test: false
      run-coverage: false 

  test-python-311:
    name: run python tests version 3.11
    uses: ./.github/workflows/reusable-python-checks.yml
    with:
      python-version: "3.11"
      run-lint: false
      run-test: true
      run-coverage: false
    
  test-python-312:
    name: run python tests version 3.12
    uses: ./.github/workflows/reusable-python-checks.yml
    with:
      python-version: "3.12"
      run-lint: false
      run-test: true
      run-coverage: false

  test-python-313:
    name: run python tests version 3.13
    uses: ./.github/workflows/reusable-python-checks.yml
    with:
      python-version: "3.13"
      run-lint: false
      run-test: true
      run-coverage: false

  coverage:
    name: Generate coverage report
    uses: ./.github/workflows/reusable-python-checks.yml
    with:
      python-version: "3.13"
      run-lint: false
      run-test: false
      run-coverage: true
