name: Container Validation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Build and test container image
    uses: ./.github/workflows/reusable-docker-build.yml
